import mongoose, { Schema } from 'mongoose';

const UserDataSchema = new Schema(
    {
        userId: { type: Schema.Types.ObjectId, ref: 'User', required: true, unique: true },
        topics: [
            {
                id: { type: String, required: true }, // The string ID generated by frontend Date.now()
                name: { type: String, required: true },
                totalSeconds: { type: Number, default: 0 }
            }
        ],
        // History uses a Map to store dynamic date keys like '2026-03-04'
        history: {
            type: Map,
            of: new Schema(
                {
                    gym: { type: Boolean, default: false },
                    // Nested map for tags inside a specific date key e.g. "tagId": 3600
                    tags: { type: Map, of: Number, default: {} }
                },
                { _id: false }
            ),
            default: {}
        }
    },
    { timestamps: true }
);

export default mongoose.models.UserData || mongoose.model('UserData', UserDataSchema);
